### ISSUE TITLE
Module 'terminal' should be 'pychado.terminal'

### ISSUE THREAD

**Issue by epruesse** [sanger-pathogens/chado-tools#12]
The way the package is structured currently, it will install two modules,  `pychado` and `terminal`. That means it unnecessarily conflicts with the package `terminal` also providing a `terminal` module.

**Comment by puethe** [comment]
Thanks, that was a legacy structure that has now been removed. With version 0.1.2 (just released and available through PyPi) only one module is installed.

**Comment by epruesse** [comment]
Thanks!
